import AnnouncementBar from "@/components/AnnouncementBar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MobileStickyNav from "@/components/MobileStickyNav";

export default function TermsAndConditionsPage() {
  return (
    <>
      <AnnouncementBar />
      <Header />
      <main style={{ padding: "60px 0", minHeight: "50vh" }}>
        <div className="container" style={{ maxWidth: 900 }}>
          <h1 style={{ fontSize: 32, fontWeight: 500, marginBottom: 40, textAlign: "center", color: "var(--heading-color)" }}>
            Terms & Conditions
          </h1>
          <div style={{ color: "var(--body-text-color)", lineHeight: 1.8, fontSize: 15 }}>
            <p style={{ marginBottom: 16 }}>
              This Is An Electronic Record In Terms Of Information Technology Act, 2000 And Rules There Under As Applicable And The Amended Provisions Pertaining To Electronic Records In Various Statutes As Amended By The Information Technology Act, 2000. This Electronic Record Is Generated By A Computer System And Does Not Require Any Physical Or Digital Signatures.
            </p>
            <p style={{ marginBottom: 16 }}>Welcome to OG Beauty.</p>
            <p style={{ marginBottom: 24 }}>
              OG Beauty provides the content and services available on this website to you subject to the following Terms and Conditions and other terms and conditions and policies which you may find throughout our website in connection with certain customer service, features or functionality as well as promotions, all of which are considered to be a part of and included within these terms and conditions (collectively, "Terms and Conditions"). By accessing or using this website, you are acknowledging that you have read, understood, and you agree, without any limitation or qualification, to be bound by these Terms and Conditions in this Agreement.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Privacy</h3>
            <p style={{ marginBottom: 24 }}>To understand our privacy practices, please review our Privacy Policy.</p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Payment Policy</h3>
            <p style={{ marginBottom: 24 }}>To understand the purchase processes of our products, please refer our Payment Policy.</p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Products And Services For Personal Use</h3>
            <p style={{ marginBottom: 24 }}>
              Any products or services provided to you on this website, are for personal use only. You are not allowed to sell or resell any of the products or services, or samples thereof, you receive from us. We reserve the right, with or without notice, to cancel or reduce the quantity of any products or services to be provided to you that we believe, in our sole discretion, may result in the violation of our Terms and Conditions.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Accuracy Of Information</h3>
            <p style={{ marginBottom: 24 }}>
              We try to be as accurate as possible when describing our products on the website. However, except as required by applicable law, we do not warrant that the product descriptions, colors, information or other content available on the website are accurate, complete, reliable, current, or error-free.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Intellectual Property</h3>
            <p style={{ marginBottom: 24 }}>
              All information and content available on the website and its "look and feel", including but not limited to trademarks, logos, service marks, text, graphics, logos, button icons, images, audio clips, data compilations, and the compilation and organization thereof (collectively, the "Content") is the property of OG Beauty, our Affiliates, partners or licensors, and is protected by laws of India, including laws governing all applicable forms of intellectual property.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Limited Licenses</h3>
            <p style={{ marginBottom: 16 }}>
              We grant you a limited, revocable, and non-exclusive license to access and make personal use of OG Beauty website. This limited license does not include the right to: (a) frame or utilize framing techniques to enclose the website or any portion thereof; (b) republish, redistribute, transmit, sell, license or download the website or any and/or all Content (except caching or as necessary to view the website); (c) make any use of the website or any and/or all Content other than personal use; (d) modify, reverse engineer or create any derivative works based upon either the website or any and/or all Content; (e) collect account information for the benefit of yourself or another party; (f) use any meta tags or any other "hidden text" utilizing any and/or all Content; or (g) use software robots, spiders, crawlers, or similar data gathering and extraction tools, or take any other action that may impose an unreasonable burden or load on our infrastructure. You must retain, without modification, all proprietary notices on the website or affixed to or contained in the website.
            </p>
            <p style={{ marginBottom: 16 }}>
              We also grant you a limited, revocable, and nonexclusive license to create a hyperlink to any page of the website for personal, non-commercial use only. A website that links to the website (i) may link to, but not replicate, any and/or all of our Content; (ii) may not imply that we are endorsing such website or its services or products; (iii) may not misrepresent its relationship with us; (iv) may not contain content that could be construed as distasteful, obscene, offensive controversial or illegal or inappropriate for any ages; (v) may not portray us or our products or services, in a false, misleading, derogatory, or otherwise offensive or objectionable manner, or associate us with undesirable products, services, or opinions. We may, in our sole discretion, request that you remove any link to the website, and upon receipt of such request, you shall immediately remove such link and cease any linking unless separately and expressly authorized in writing by us to resume linking.
            </p>
            <p style={{ marginBottom: 24 }}>
              Any unauthorized use by you of our website or any and/or all of our Content automatically terminates the limited licenses set forth in this Section without prejudice to any other remedy provided by applicable law or these Terms and Conditions.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Your Obligations And Responsibilities</h3>
            <p style={{ marginBottom: 24 }}>
              You shall comply with these Terms and Conditions and the special warnings or instructions for access or use posted on the website. You may not make any change or alteration to the website or any Content or services that may appear on this website and may not impair in any way the integrity or operation of the website. Without limiting the generality of any other provision of these Terms and Conditions, if you default negligently or willfully in any of the obligations set forth in these Terms and Conditions, you shall be liable for all the losses and damages that this may cause to OG Beauty, our Affiliates, partners or licensors.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Special Features, Functionality And Events</h3>
            <p style={{ marginBottom: 24 }}>
              OG Beauty may offer certain special features and functionality or events (such as contests, promotions or other offerings) which may (a) be subject to terms of use, rules and/or policies in addition to or in lieu of these Terms and Conditions; and (b) be offered by us or by third parties. If you choose to take advantage of these offerings, you agree that your use of those offerings will be subject to such additional or separate terms of use, rules and/or policies.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>User Content</h3>
            <p style={{ marginBottom: 16 }}>
              When you transmit, upload, post, e-mail or otherwise make available data, text, software, music, sound, photographs, graphics, images, videos, messages or other materials ("User Content") on the website, you are entirely responsible for such User Content. Such User Content constitutes a Submission under Section 10 above. This means that all third parties, and not we, are entirely responsible for all User Content that they post to the website. You agree not to engage in or assist or encourage others to engage in transmitting, uploading, posting, e-mailing or otherwise making available on the website User Content that (a) is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, pornographic, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; (b) you do not have a right to make available under any law or under contractual or fiduciary relationships; (c) is known by you to be false, inaccurate or misleading; (d) you were compensated for or granted any consideration by any third party; or (e) infringes any patent, trademark, trade secret, copyright or other proprietary and/or intellectual property rights of any party. In addition, you agree not to transmit, upload, post, e-mail, or otherwise make available any software viruses, unsolicited or unauthorized advertising, solicitation or promotional material, including chain letters, mass mailings, or any form of "spam". You further agree not to (i) impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with any person or entity; (ii) "stalk" or otherwise harass including advocating harassment of another, entrap or harm any third party including harming minors in any way; (iii) forge headers or otherwise manipulate identifiers in order to disguise the origin of any User Content; (iv) intentionally or unintentionally violate any applicable local, state, national or international law; or (v) collect or store personally identifiable data about other users.
            </p>
            <p style={{ marginBottom: 16 }}>
              We do not endorse or control the User Content transmitted or posted on the OG Beauty website and therefore, we do not guarantee the accuracy, integrity or quality of User Content. You understand that by using this website, you may be exposed to User Content that is offensive, indecent or objectionable to you. Under no circumstances will we be liable in any way for any User Content, including, without limitation, for any errors or omissions in any User Content, or for any loss or damage of any kind incurred by you as a result of the use of any User Content transmitted, uploaded, posted, e-mailed or otherwise made available via the website.
            </p>
            <p style={{ marginBottom: 24 }}>
              You acknowledge that we have the right (but not the obligation) in our sole discretion to refuse to post or remove any User Content and we reserve the right to change, condense, or delete any User Content. Without limiting the generality of the foregoing or any other provision of these Terms and Conditions, we have the right to remove any User Content that violates these Terms and Conditions or is otherwise objectionable and we reserve the right to refuse service without prior notice for any users who violate these Terms and Conditions or infringe the rights of others.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Copyright Complaints</h3>
            <p style={{ marginBottom: 24 }}>
              We respect the intellectual property of others. If you believe that copyrighted materials have been copied in a way that constitutes copyright infringement, please send an email or written notice to us for notices of infringement and provide the following: (i) identification of the copyrighted work(s) that you claim has been infringed and that you are the copyright owner or authorized to act on the copyright owner's behalf; (ii) a description of the material that you claim is infringing and the location of the material on the website; (iii) your address, telephone number and email address to: ecomm@ogbeauty.in
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Representations And Warranties And Limitation Of Liability</h3>
            <p style={{ marginBottom: 16 }}>
              OG Beauty website is presented "As Is". We make no representations or warranties of any kind whatsoever, express or implied, in connection with these terms and conditions or the site, including but not limited to warranties of merchantability, non-infringement or fitness for a particular purpose.
            </p>
            <p style={{ marginBottom: 16 }}>
              You agree that, to the fullest extent permitted by applicable law, we will not be responsible or liable (whether in contract, tort (including negligence) or otherwise), under any circumstances, for any (a) interruption of business; (b) access delays or access interruptions to the site; (c) data non-delivery, mis-delivery, corruption, destruction or other modification; (d) loss or damages of any sort incurred as a result of dealings with or the presence of off-website links on the website; (e) computer viruses, system failures or malfunctions which may occur in connection with your use of the site, including during hyperlink to or from third party websites (f) any inaccuracies or omissions in content or (g) events beyond our reasonable control.
            </p>
            <p style={{ marginBottom: 16 }}>
              OG Beauty products are based on genuine and authentic formulations. Though enormous efforts are made and precautions taken to render the products absolutely safe for human use, it is possible that certain ingredients may cause allergic reactions to certain individuals or adversely affect individuals with pre-existing medical conditions. Please make yourself aware of the ingredients and usage instructions accompanying each of our products to make sure that they are safe for you to use. It will be your sole responsibility to take proper precaution/ professional medical/ dermatological advice before using any of our personal care products that you may be allergic to. You agree that OG Beauty will not be responsible or liable for any product related issues including without limitation any allergic reactions to you on account of usage of our products. For any purchases made through the OG Beauty website, you will inter alia be governed by the limitation of liability and disclaimer conditions provided in more detail with the product packaging/leaflets.
            </p>
            <p style={{ marginBottom: 16 }}>
              Further, to the fullest extent permitted by law, we will not be liable for any indirect, special, punitive, incidental, or consequential damages of any kind (including lost profits) related to the website or your use thereof regardless of the form of action whether in contract, tort (including negligence) or otherwise, even if we have been advised of the possibility of such damages and in no event shall our maximum aggregate liability exceed Indian Rupees 1000 only.
            </p>
            <p style={{ marginBottom: 24 }}>
              You agree that no claims or action arising out of, or related to, the use of the website or these terms and conditions may be brought by you more than one (1) year after the cause of action relating to such claim or action arose.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Indemnification</h3>
            <p style={{ marginBottom: 24 }}>
              You agree to defend, indemnify and hold us harmless for any loss, damages or costs, including reasonable attorneys' fees, resulting from any third party claim, action, or demand resulting from your use of OG Beauty or breach of these Terms and Conditions. You also agree to indemnify us for any loss, damages, or costs, including reasonable attorneys' fees, resulting from your use of software robots, spiders, crawlers, or similar data gathering and extraction tools, or any other action you take that imposes an unreasonable burden or load on our infrastructure.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Disputes</h3>
            <p style={{ marginBottom: 16 }}>
              With respect to any dispute regarding the website, all rights and obligations and all actions contemplated by these Terms and Conditions shall be governed by the laws of India and the courts of Ahmedabad, India, as if the Terms and Conditions were a contract wholly entered into and wholly performed within Ahmedabad, India. To the fullest extent permitted by applicable law, any dispute, differences or claim arising out of your visit to the OG Beauty website shall be referred to the sole Arbitrator appointed by the Executive Director of OG Beauty in accordance with the law. The venue of such arbitration shall be at Ahmedabad, India and the award of the Arbitrator shall be final and binding on all parties and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these Terms and Conditions shall be joined to an arbitration involving any other party subject to this Terms and Conditions, whether through class arbitration proceedings or otherwise.
            </p>
            <p style={{ marginBottom: 24 }}>
              To the extent arbitration is not permitted by applicable law, any dispute relating in any way to your visit to the website shall be submitted to an appropriate court or other judicial body in Ahmedabad, India, as applicable, without prejudice to the applicable law and all applicable provisions of this Section, and subject to our right to seek injunctive or other appropriate relief in any court, if you have in any manner violated or threatened to violate our intellectual property rights and you consent to exclusive jurisdiction and venue in such courts.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Consent To Receive Notices Electronically By Posting On The Website And Via Email</h3>
            <p style={{ marginBottom: 16 }}>
              You consent to receive any agreements, notices, disclosures and other communications (collectively, "Notices") to which these Terms and Conditions refer from us electronically including without limitation by email or by posting notices on this website. You agree that all Notices that we provide to you electronically satisfy any legal requirement that such communications be in writing in English. To withdraw your consent to receive Notices electronically, you must notify us of your withdrawal of such consent by emailing us at: ecomm@ogbeauty.in and discontinue your use of this website.
            </p>
            <p style={{ marginBottom: 24 }}>
              Please note that this consent to receive Notices is entirely separate from any election you may make with respect to receipt of marketing communications. Your options with respect to receipt of marketing communications are set forth in our Privacy Policy.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>General</h3>
            <p style={{ marginBottom: 16 }}>
              You acknowledge and agree that these Terms and Conditions constitute the complete and exclusive agreement between us concerning your use of the website, and supersede and govern all prior proposals, agreements, or other communications.
            </p>
            <p style={{ marginBottom: 16 }}>
              We reserve the right, in our sole discretion, to change these Terms and Conditions at any time by posting the changes on the website and providing notice of such change. Any changes are effective immediately upon posting to the Site and release of notice of such change. Your continued use of the website thereafter constitutes your agreement to all such changed Terms and Conditions. We may, with or without prior notice, terminate any of the rights granted by these Terms and Conditions. You shall comply immediately with any termination or other notice, including, as applicable, by ceasing all use of the website.
            </p>
            <p style={{ marginBottom: 24 }}>
              Nothing contained in these Terms and Conditions shall be construed as creating any agency, partnership, or other form of joint enterprise between us. Our failure to require your performance of any provision hereof shall not affect our full right to require such performance at any time thereafter, nor shall our waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself. In the event that any provision of these Terms and Conditions shall be unenforceable or invalid under any applicable law or be so held by any applicable arbitral award or court decision, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole but these Terms and Conditions shall be modified, to the extent possible, by the adjudicating entity to most fully reflect the original intent of the parties as reflected in the original provision.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>B2G1 offer</h3>
            <ul style={{ paddingLeft: 20, marginBottom: 24, display: "flex", flexDirection: "column", gap: 8 }}>
              <li>1. The Offer is applicable to all products available on the official OG Beauty website.</li>
              <li>2. The item(s) with the lowest price will be considered as FREE. If three identical items are not ordered, the least expensive item will be deducted.</li>
              <li>3. B2G1 offer is exclusive to the official website and is not valid on external marketplaces where OG Beauty products are sold.</li>
              <li>4. Offer details may change or be discontinued without prior notice, with the consent of OG Beauty.</li>
              <li>5. Offers are non-transferable and cannot be exchanged, sold, or bartered for cash.</li>
              <li>6. Products can be mixed and matched but must be purchased in multiples of 3 to qualify.</li>
              <li>7. If the lower-priced product is returned (subject to return eligibility), a refund will be issued based on the amount paid. If the higher-priced product is returned (subject to return eligibility), the refund will be calculated based on the amount paid, minus the discount applied to the lower-priced product.</li>
              <li>8. No price adjustments will be made for prior purchases.</li>
              <li>9. If the B2G1 coupon code is not applied at checkout, the customer will not be eligible for an additional product or discount after the purchase.</li>
              <li>10. Offer valid until stocks last.</li>
            </ul>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Free Pouch Offer</h3>
            <ul style={{ paddingLeft: 20, marginBottom: 24, display: "flex", flexDirection: "column", gap: 8 }}>
              <li>1. This offer is valid only on cart orders with a total value of ₹749 or more.</li>
              <li>2. The cart value of ₹749 must be met before or after applying any discount code.</li>
              <li>3. Shipping and Cash on Delivery (COD) charges are excluded from the ₹749 cart total.</li>
              <li>4. The free pouch must be selected at the time of checkout. It cannot be added later on request once the order is placed.</li>
              <li>5. This offer is valid for a limited time only and may be modified or withdrawn at the discretion of the brand.</li>
              <li>6. One free pouch per eligible order.</li>
            </ul>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Grievance officer</h3>
            <p style={{ marginBottom: 16 }}>
              The name and contact details of the Grievance Officer to handle any complaints in relation to the sale of Products or use of this Website are provided below. All complaints will be acknowledged within 48 hours (Working Days), and will be addressed no later than 1 month from the date of complaint received.
            </p>
            <p style={{ marginBottom: 16 }}>
              Email: ecomm@ogbeauty.in<br/>
              Time: Monday-Saturday (From 11:00 Am to 6:00pm)
            </p>
            <p style={{ marginBottom: 16 }}>
              The user shall not assign its rights or obligations under these Terms and the Privacy Policy to a third party.
            </p>
            <p style={{ marginBottom: 24 }}>
              If you have any questions regarding these Terms and Conditions, please email us at: ecomm@ogbeauty.in
            </p>

            <p style={{ marginBottom: 40, fontWeight: 500 }}>
              Worldwide Copyright © OG Beauty. (brand owners OG Beauty). All worldwide rights reserved.
            </p>

            <h3 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12, color: "var(--heading-color)" }}>Coupon T&C<br/>OG Luxury Perfumes – Coupon Terms & Conditions</h3>
            <p style={{ marginBottom: 16 }}>TRY. LOVE. UPGRADE.</p>
            <p style={{ marginBottom: 16 }}>By redeeming this coupon, you agree to the following Terms & Conditions:</p>
            <ul style={{ paddingLeft: 20, marginBottom: 24, display: "flex", flexDirection: "column", gap: 8 }}>
              <li>This coupon entitles the holder to 50% OFF on the MRP of one (1) 100ml bottle of their chosen OG Luxury fragrance.</li>
              <li>The coupon is valid for a single use only and cannot be reused once redeemed.</li>
              <li>The offer is applicable only on eligible 100ml fragrance bottles and cannot be combined with any other promotion, discount, offer, voucher, or coupon code.</li>
              <li>The coupon must be redeemed through the designated QR code or redemption link provided.</li>
              <li>The coupon is non-transferable, has no cash value, and cannot be exchanged for cash, credit, or any other benefit.</li>
              <li>Products purchased using this coupon are not eligible for return, refund, replacement, exchange, or cancellation.</li>
              <li>The coupon is intended solely for the recipient to whom it has been issued and may be subject to verification.</li>
              <li>Any misuse, duplication, alteration, or unauthorized distribution of the coupon may result in its cancellation without notice.</li>
              <li>OG Luxury reserves the right to modify, suspend, or withdraw this offer at its sole discretion without prior notice.</li>
              <li>Redemption of this coupon constitutes acceptance of these Terms & Conditions.</li>
            </ul>
          </div>
        </div>
      </main>
      <Footer />
      <MobileStickyNav />
    </>
  );
}
